@ECHO OFF
taskkill /F /FI "WINDOWTITLE eq Input1 - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Input2 - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Input3 - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Filler1 - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Filler2 - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Printer - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Output - nodemon*"
taskkill /F /FI "WINDOWTITLE eq HandlingRobot - nodemon*"

taskkill /F /FI "WINDOWTITLE eq Input1 - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Input2 - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Input3 - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Filler1 - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Filler2 - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Printer - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Output - nodemon*"
taskkill /F /FI "WINDOWTITLE eq HandlingRobot - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Input1 - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Input2 - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Input3 - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Filler1 - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Filler2 - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Printer - nodemon*"
taskkill /F /FI "WINDOWTITLE eq Output - nodemon*"
taskkill /F /FI "WINDOWTITLE eq HandlingRobot - nodemon*"
